name: calidemo
location: westus2
apiVersion: '2021-07-01'
properties:
  containers:
  - name: streamlitapp
    properties:
      image: calidemo.azurecr.io/azure_demo:v1
      ports:
      - port: 80
        protocol: TCP
      - port: 443
        protocol: TCP
      resources:
        requests:
          cpu: 2.0
          memoryInGB: 1.5
  imageRegistryCredentials:
  - server: calidemo.azurecr.io
    username: calidemo
    password: p6cTCKrBibuu7zUc+72BPgwZZoNMLsX0
  restartPolicy: Never
  ipAddress:
    ports:
    - port: 443
      protocol: TCP
    - port: 80
      protocol: TCP
    type: Public
    dnsNameLabel: calihouseprice90
  osType: Linux
tags: null
type: Microsoft.ContainerInstance/containerGroups